import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Nav from "@/components/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Meu projeto em Next",
  description: "Generated by create next app",
};

// Aula 05 - Layout
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-purple-600 text-center p-8">
          <Nav/>
          <h1>Cabeçalho da página</h1>
        </div>
        {/* Aula 07 - link Ativo */}

        {children}

        {/* Aula 06 - components */}
        <Footer />
      </body>
    </html>
  );
}
