### GET all tasks
GET http://localhost:3000/tasks
Accept: application/json

###

### GET a single task by ID
GET http://localhost:3000/tasks/1
Accept: application/json

###

### CREATE a new task
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "title": "Lavar o carro",
    "description": "Lavar o carro no sábado"
}

###

### UPDATE a task by ID
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
    "title": "Tarefa atualizada",
    "description": "Descrição atualizada"
}

###

### DELETE a task by ID
DELETE http://localhost:3000/tasks/1
Accept: application/json

###